services:
  user:
    depends_on:
      - db
    build: /user
    ports:
      - "5113:80"
    links:
      - db
  db:
    image: mysql:8.0.32
    ports:
      - "5114:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msc
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
