services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msc
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5114:3306"
  # For some reason, the user service is canno't connect to db from within docker image.
  user:
    depends_on:
      - db
    build: /User
    ports:
      - "5113:80"
    environment:
      # - Cors__AllowedOrigins__0__=http://127.0.0.1:5173
      - ConnectionStrings__DefaultConnection=server=db;user=root;password=root;database=msc;port=3306
      - JWT__Issuer=None
      - JWT__Audience=None
      - JWT__Key=LJI+iKUWnHq2aW8nUUxiqTzXPEY96hRGvCrBpA5dyX4gNJfrbZplbjXAVq1Jh6udXvtD4bRoAWd7CQL2ar2dQA==
  groups:
    depends_on:
      - db
    build: /groupmanagement
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306